name: Android Build Pre Setting
description: Android Build Pre Setting
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clone Submodule
      run: git clone https://github.com/beomjo/android-compilation.git