name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit_test:
    name: UnitTest
    needs: pre_env_setting
    runs-on: ubuntu-latest
    steps:
      - name: Pre Setting
        uses: user/composite@v1
        
      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: reports
          path: app/build/test-results # path to where the xml test results are stored