name: Upload AAB to PlayStore

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clone Submodule
        run: git clone https://github.com/beomjo/android-compilation.git
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: reports
          path: app/build/test-results # path to where the xml test results are stored
      - name: Clean Project
        run: ./gradlew clean
      - name: Build AAB
        run: ./gradlew bundleRelease --stacktrace
      - name: Signing AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE_64 }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - name: Upload AAB to Github Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: white_noise_player
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

